# Generated by Django 2.1.7 on 2019-03-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190326_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='githubUrl',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='hostName',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='lastName',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='author',
            name='password',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='userName',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='comment',
            name='contentType',
            field=models.CharField(choices=[('text/markdown', 'text/markdown'), ('text/plain', 'text/plain')], default='text/plain', max_length=32),
        ),
    ]
