# Generated by Django 2.1.7 on 2019-03-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190327_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
