# Generated by Django 2.1.7 on 2019-03-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_node_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='post_id',
        ),
        migrations.AddField(
            model_name='node',
            name='password',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='node',
            name='username',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
